ALWAYS_PARSE = False
ALWAYS_REDUCE = False

MIN_GAP_DIS = 5.0
MAX_END_DISTANCE = 10.0

REDUCTION_DISTANCE = 1000.0
GPX_FILE_PATTERN = "*.gpx"
POINTS_ITERATOR_GAP = 10

ROUTES_FOUND_END = 1
MAX_DETOUR = 5
